let burger = document.querySelector('.burger')
let nav = document.querySelector('.navbar-links')
let line1 = document.getElementById('line1')
let line2 = document.getElementById('line2')
let line3 = document.getElementById('line3')
console.log(line1, line2, line3)
console.log(burger, nav)
burger.addEventListener('click', () => {
    console.log('clicked')
    line1.classList.toggle('line1-a')
    line2.classList.toggle('line2-a')
    line3.classList.toggle('line3-a')
    nav.classList.toggle('visible')
})